const Courses = [
    {
        id: '1',
        title: "Web Development",
        image: require('../../assests/webd.jpg'),
        description: "Web development is the work involved in developing a website for the Internet (World Wide Web) or an intranet (a private network). ",
        course1: "HTML",
        course2: "CSS",
        course3: "Javascript",
        Price: 5000,
    },
    {
        id: '2',
        title: "Graphic Designing",
        image: require('../../assests/gd.jpg'),
        description: "Web development is the work involved in developing a website for the Internet (World Wide Web) or an intranet (a private network). ",
        course1: "Photoshop",
        course2: "Figma",
        course3: "Adobe XD",
        Price: 3000,
    }, {
        id: '3',
        title: "Coding Fundamentals",
        image: require('../../assests/coding.jpg'),
        description: "Web development is the work involved in developing a website for the Internet (World Wide Web) or an intranet (a private network). ",
        course1: "Java",
        course2: "IntelliJ",
        Price: 2500,
    },
    {
        id: '4',
        title: "Data Science",
        image: require('../../assests/datas.jpg'),
        description: "Web development is the work involved in developing a website for the Internet (World Wide Web) or an intranet (a private network). ",
        course1: "Python",
        course2: "Ruby",
        course3: "Pycharm",
        Price: 4000,
    },
    {
        id: '5',
        title: "React-Native",
       image: require('../../assests/react.jpg'),
        description: "Web development is the work involved in developing a website for the Internet (World Wide Web) or an intranet (a private network). ",
        course1: "React",
        course2: "Firebase",
        Price: 5500,
    },
];
export default Courses;